# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 淘推荐
email: 247084776@qq.com
description: > # this means to ignore newlines until "baseurl:"
  淘宝精品宝贝推荐.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://shop.lijingfeng.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
gems: [jekyll-paginate]
paginate: 5
paginate_path: "blog/page:num"